#!/usr/bin/env python3
"""Write an assembly file that references every C entrypoint the vendored llvm-libc builds.

  libc_link_probe.py <libc.cmake> <out.S>

Reads the active (not commented) lines of LIBC_SOURCE_FILES in libc.cmake. An entrypoint is a source
under src/<header>/ outside src/__support and src/errno; its name is the file stem (src/math/generic/acosf.cpp ->
acosf). The .S holds one `.word <name>` per entrypoint in a section the image keeps through the
symbol kvasir_libc_link_probe, so every entrypoint - and everything it calls - is linked: a
symbol the libc refers to and nothing defines fails the link.
"""
import re
import sys
from pathlib import Path


# sources that are not one entrypoint named like the file: the internals, and errno's storage (libc_errno.cpp defines
# __llvm_libc_errno and Errno::operator=, which the entrypoints that set errno pull in)
NOT_ENTRYPOINTS = ("src/__support/", "src/errno/")


def entrypoints(cmake: Path) -> list[str]:
    text = cmake.read_text()
    block = re.search(r"set\(LIBC_SOURCE_FILES\n(.*?)\n\)", text, re.S)
    if block is None:
        sys.exit(f"{cmake}: no set(LIBC_SOURCE_FILES ...)")
    names = []
    for line in block.group(1).splitlines():
        source = line.strip()
        if not source or source.startswith("#"):
            continue
        if not source.startswith("src/") or source.startswith(NOT_ENTRYPOINTS):
            continue
        if not source.endswith((".cpp", ".c")):
            continue
        names.append(Path(source).stem)
    return sorted(set(names))


def main() -> None:
    cmake, out = Path(sys.argv[1]), Path(sys.argv[2])
    names = entrypoints(cmake)
    lines = ["// generated by libc_link_probe.py from libc.cmake - do not edit",
             "    .syntax unified",
             # an architecture every Kvasir core links with: GNU ld refuses the assembler's default (v4T) next to
             # v8-M objects, and a tree need not pass -mcpu to .S files
             "    .arch armv6-m",
             '    .section .rodata.kvasir_libc_link_probe,"a",%progbits',
             "    .p2align 2",
             "    .globl kvasir_libc_link_probe",
             "kvasir_libc_link_probe:"]
    lines += [f"    .word {name}" for name in names]
    lines += ["    .globl kvasir_libc_link_probe_count",
              "    .set kvasir_libc_link_probe_count, " + str(len(names)), ""]
    text = "\n".join(lines)
    if not out.exists() or out.read_text() != text:   # unchanged: no rebuild
        out.write_text(text)


if __name__ == "__main__":
    main()
