FROM kvasirio/build_environment:latest AS kvasir_dev

ENV KVASIR_ROOT=/opt/kvasir
COPY . ${KVASIR_ROOT}/
RUN git config --global --add safe.directory ${KVASIR_ROOT}

ENTRYPOINT ["/opt/kvasir/scripts/entrypoint.sh"]
