# ARM Compiler Common Configuration Shared settings for ARM cross-compilation toolchains Sets up system properties and
# common compiler flags for embedded ARM targets

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE NEVER)

set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES)
set(CMAKE_CROSSCOMPILING True)

set(arm_compiler_common_flags -ffreestanding)

set(SPEC_REPLACEMENT_STRING spec_replace)
set(SPEC_REPLACEMENT_EMPTY_MARKER NOTHING_TO_REPLACE)

# the vendored libc++'s configuration, shared by arm_clang.cmake and arm_gcc.cmake so the two cannot drift
set(libcxx_profile_flags
    -D_LIBCPP_ABI_VERSION=2
    -D_LIBCPP_ABI_NAMESPACE=__2
    -D_LIBCPP_HAS_MONOTONIC_CLOCK=1
    -D_LIBCPP_HAS_THREADS=0
    -D_LIBCPP_HAS_TERMINAL=0
    -D_LIBCPP_HAS_FILESYSTEM=0
    -D_LIBCPP_HAS_RANDOM_DEVICE=0
    -D_LIBCPP_HAS_LOCALIZATION=0
    -D_LIBCPP_HAS_UNICODE=0
    -D_LIBCPP_HAS_WIDE_CHARACTERS=0
    -D_LIBCPP_HARDENING_MODE_DEFAULT=_LIBCPP_HARDENING_MODE_FAST
    -D_LIBCPP_ASSERTION_SEMANTIC_DEFAULT=_LIBCPP_ASSERTION_SEMANTIC_HARDENING_DEPENDENT
    -D_LIBCPP_HAS_TIME_ZONE_DATABASE=0
    -D_LIBCPP_LIBC_NEWLIB=0
    -D_LIBCPP_LIBC_PICOLIBC=0)
